### ISSUE TITLE
Support for self-signed certs?

### ISSUE THREAD

**Issue by Panoplos** [apollographql/apollo-cli#199]
When developing locally, it is important to support self-signed certs. I believe adding this is quite simple and can be disabled by default for security reason.

**Comment by martijnwalraven** [comment]
Do you mean supporting self-signed certs for downloading the schema?

**Comment by Panoplos** [comment]
Yes

**Comment by Panoplos** [comment]
Note that I implemented this in gql2flow (before knowing about this tool).
https://github.com/joarwilk/gql2flow/pull/30

**Comment by martijnwalraven** [comment]
@Panoplos: Seeing as you've already implemented this, a PR would be very welcome!

**Comment by schleumer** [comment]
@xrd even when using `--insecure`, `--insecure=true`, `-K`, `-K true`, or any other variation i still get `error: Error while fetching introspection query result: Protocol "http:" not supported. Expected "https:"`, i think that flag means that it can be a insecure connection somehow but not a self-signed cert or HTTP, a look at source: https://github.com/apollographql/apollo-codegen/blob/master/src/downloadSchema.ts#L20 and removing that line and its reference helped me to download a schema via HTTP

**Comment by maarekj** [comment]
Has `--insecure` option disappeared ?

**Comment by SimonCropp** [comment]
i have the same question as @maarekj

**Comment by robertomg** [comment]
We need to support this feature. Our team is also using a self-signed certificate for development.

**Comment by maarekj** [comment]
This option has disappeared again

**Comment by hally9k** [comment]
I'm also having trouble getting this working 😕
